# Generated by Django 5.1.1 on 2025-01-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='dateReturn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
